spring:
    application:
        name: erp

# DB 설정
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@localhost:1521/xe
        username: finalproject
        password: java1234

# JPA 설정
    jpa:
        database: oracle
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        enabled: true
        cache: false

    # Pageable 기본값
    data:
        web:
            pageable:
                default-page-size: 10



server:
    port: 8090


# XML Mapper Locations
mybatis:
    mapper-locations: classpath:/mapper/*.xml
